# Generated by Django 6.0.6 on 2026-06-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan_subscription_serviceflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='pin_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membership',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
