# Generated by Django 6.0.6 on 2026-06-21 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('shop', 'Boutique'), ('warehouse', 'Entrepôt'), ('stall', 'Stand de marché')], default='shop', max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Emplacement',
                'verbose_name_plural': 'Emplacements',
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('reorder_threshold', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Niveau de stock',
                'verbose_name_plural': 'Niveaux de stock',
                'constraints': [models.UniqueConstraint(fields=('product', 'variant', 'location'), name='unique_stock_level')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('transfer', 'Transfert'), ('adjustment', 'Ajustement')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unit', models.CharField(default='unité', max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('client_uuid', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productvariant')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('tenant', 'client_uuid'), name='unique_movement_client_uuid')],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_unit', models.CharField(max_length=32)),
                ('to_unit', models.CharField(max_length=32)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='inventory.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': "Conversion d'unité",
                'verbose_name_plural': "Conversions d'unité",
                'constraints': [models.UniqueConstraint(fields=('product', 'from_unit', 'to_unit'), name='unique_unit_conversion')],
            },
        ),
    ]
