# Generated by Django 6.0.6 on 2026-06-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_price_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='type',
            field=models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie'), ('transfer', 'Transfert'), ('adjustment', 'Ajustement'), ('loss', 'Perte / casse')], max_length=16),
        ),
    ]
