# Generated by Django 6.0.6 on 2026-06-23 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom / Raison sociale')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone (E.164)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('type', models.CharField(choices=[('individual', 'Particulier'), ('business', 'Entreprise')], default='individual', max_length=20, verbose_name='Type de client')),
                ('niu', models.CharField(blank=True, help_text="Numéro d'Identifiant Unique fiscal (clients entreprises).", max_length=50, null=True, verbose_name='NIU')),
                ('trust_level', models.CharField(choices=[('new', 'Nouveau'), ('reliable', 'Fiable'), ('at_risk', 'À risque')], default='new', max_length=20, verbose_name='Niveau de confiance')),
                ('is_express', models.BooleanField(default=False, verbose_name='Client express')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
    ]
