# Generated by Django 6.0.6 on 2026-06-27 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_token_fields'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde de dette'),
        ),
        migrations.CreateModel(
            name='DebtMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('sale', 'Vente à crédit'), ('repayment', 'Remboursement'), ('adjustment', 'Ajustement')], max_length=20, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('reference', models.CharField(blank=True, max_length=255, verbose_name='Référence')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Note')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_movements', to='crm.customer', verbose_name='Client')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Mouvement de dette',
                'verbose_name_plural': 'Mouvements de dette',
                'ordering': ['created_at'],
            },
        ),
    ]
