# Generated by Django 6.0.6 on 2026-06-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_debt_balance_debtmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pricing_tier',
            field=models.CharField(choices=[('retail', 'Détail (grand public)'), ('reseller', 'Petit revendeur'), ('wholesale', 'Grossiste')], default='retail', max_length=20, verbose_name='Segment tarifaire'),
        ),
    ]
