# Generated by Django 6.0.6 on 2026-06-23 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('settled', 'Soldé')], default='open', max_length=20, verbose_name='Statut')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Relevé de crédit',
                'verbose_name_plural': 'Relevés de crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('momo', 'Mobile Money (MTN)'), ('orange_money', 'Orange Money')], max_length=20, verbose_name='Moyen de paiement')),
                ('status', models.CharField(choices=[('declared', 'Déclaré'), ('confirmed', 'Confirmé')], default='declared', max_length=20, verbose_name='Statut')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='supplier.creditstatement', verbose_name='Relevé')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('charge', 'Débit (achat)'), ('adjustment', 'Ajustement'), ('credit_note', 'Avoir')], max_length=20, verbose_name="Type d'écriture")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='supplier.creditstatement', verbose_name='Relevé')),
            ],
            options={
                'verbose_name': 'Écriture de crédit',
                'verbose_name_plural': 'Écritures de crédit',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_ceiling', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Plafond de crédit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='supplier.supplier', verbose_name='Fournisseur')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Lien fournisseur',
                'verbose_name_plural': 'Liens fournisseurs',
                'ordering': ['supplier__name'],
                'unique_together': {('tenant', 'supplier')},
            },
        ),
        migrations.AddField(
            model_name='creditstatement',
            name='supplier_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='supplier.supplierlink', verbose_name='Lien fournisseur'),
        ),
    ]
