"""
Django settings for kenpro_store project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Tiers
    'rest_framework',
    'drf_spectacular',
    'django_celery_beat',
    # Apps KENPRO
    'accounts',
    'inventory',
    'crm',
    'supplier',
    'sales',
    'repair',
    'mobilemoney',
    'notifications',
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Résolution du tenant courant (SaaS ou on-premise)
    'kenpro_store.middleware.TenantMiddleware',
]

# ---------------------------------------------------------------------------
# Résolution de tenant
# ---------------------------------------------------------------------------

# Vide = mode SaaS (sous-domaine ou header X-Tenant-Slug).
# Renseigné = mode on-premise : un seul tenant pour ce déploiement.
SINGLE_TENANT_SLUG = os.environ.get("SINGLE_TENANT_SLUG", "")

# Chemins qui ne nécessitent pas de tenant résolu.
TENANT_EXEMPT_PATHS = [
    "/admin/",
    "/api/schema/",
    "/api/docs/",
    "/api/redoc/",
    "/api/v1/accounts/register/",
    "/api/v1/accounts/password-reset/",
    "/api/v1/accounts/password/change/",
    "/api/v1/accounts/pin-reset/",
]

PASSWORD_RESET_TOKEN_TTL_MINUTES = 15

# URL publique du frontend — utilisée pour générer les liens partageables
# (reçu WhatsApp, catalogue en ligne).
FRONTEND_URL = os.environ.get("FRONTEND_URL", "https://app.kenpro.cm")

# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CELERY_TIMEZONE = "Africa/Douala"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# ---------------------------------------------------------------------------
# WhatsApp Business API (optionnel — si non configuré, alertes désactivées)
# ---------------------------------------------------------------------------
WHATSAPP_API_URL = os.environ.get("WHATSAPP_API_URL", "")
WHATSAPP_API_TOKEN = os.environ.get("WHATSAPP_API_TOKEN", "")
WHATSAPP_FROM_PHONE_ID = os.environ.get("WHATSAPP_FROM_PHONE_ID", "")

# Durée de validité des jetons de réinitialisation PIN (en minutes)
PIN_RESET_TOKEN_TTL_MINUTES = 15

ROOT_URLCONF = 'kenpro_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kenpro_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "kenpro_store.pagination.CustomPagination",
    "PAGE_SIZE": 10,
    "EXCEPTION_HANDLER": "kenpro_store.exception_handler.custom_exception_handler",
    # GET public, mutations (POST/PUT/PATCH/DELETE) requièrent un utilisateur authentifié.
    # Évite les ValueError sur request.user = AnonymousUser dans les perform_create.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# ---------------------------------------------------------------------------
# drf-spectacular — configuration du schéma OpenAPI
# ---------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "KENPRO API",
    "DESCRIPTION": "Système d'exploitation du commerce africain — API backend.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Noms explicites pour les enums partagés entre plusieurs modèles.
    # Sans ça, drf-spectacular génère des noms auto-générés illisibles
    # (ex. Status35eEnum) dès qu'un même nom de champ est utilisé dans
    # plusieurs sérialiseurs avec des choices différents.
    # Noms d'enums explicites — format chemin pointé, sans ambiguïté avec TextChoices.
    # La clé est le nom dans le schéma OpenAPI ; la valeur est le chemin vers la
    # classe TextChoices (drf-spectacular en extrait les valeurs et les labels).
    # Noms d'enums explicites pour éviter les collisions drf-spectacular.
    # Règle : chemin pointé pour les TextChoices internes, liste de valeurs
    # pour les anciens choix sous forme de liste (ex. inventory).
    "ENUM_NAME_OVERRIDES": {
        # --- CRM (TextChoices) ---
        "CustomerTypeEnum":          "crm.models.Customer.Type",
        "TrustLevelEnum":            "crm.models.Customer.TrustLevel",
        # --- Inventory (ancienne syntaxe TYPE_CHOICES) ---
        "LocationTypeEnum":          ["shop", "warehouse", "stall"],
        "MediaAssetTypeEnum":        ["image", "video"],
        "StockMovementTypeEnum":     ["in", "out", "transfer", "adjustment"],
        "ProductStatusEnum":         ["draft", "active", "archived"],
        # --- Sales (TextChoices) ---
        "SaleChannelEnum":           "sales.models.Sale.Channel",
        "SaleStatusEnum":            "sales.models.Sale.Status",
        "SalePaymentMethodEnum":     "sales.models.Payment.Method",
        "SalePaymentStatusEnum":     "sales.models.Payment.Status",
        # --- Supplier (TextChoices) ---
        "CreditStatementStatusEnum": "supplier.models.CreditStatement.Status",
        "CreditEntryTypeEnum":       "supplier.models.CreditEntry.Type",
        "SupplierPaymentMethodEnum": "supplier.models.CreditPayment.Method",
        "SupplierPaymentStatusEnum": "supplier.models.CreditPayment.Status",
        # --- Repair (TextChoices) ---
        "DeviceTypeEnum":            "repair.models.Device.Type",
        # Couvre RepairTicket.status ET TicketTransitionSerializer.to_status :
        # même jeu de valeurs → même enum, élimine le warning ToStatusEnum.
        "RepairStatusEnum":          "repair.models.RepairTicket.Status",
    },
    # Génère un uuid pour le paramètre pk sur les viewsets dont
    # get_queryset() est dynamique (drf-spectacular ne peut pas l'appeler
    # sans request, donc il ne connaît pas le modèle).
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],
}
