# Generated by Django 6.0.6 on 2026-06-27 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_plan_subscription_serviceflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlertConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Alertes activées')),
                ('whatsapp_phone', models.CharField(help_text='Format E.164 : +237600000001', max_length=20, verbose_name='Numéro WhatsApp destinataire')),
                ('send_time', models.CharField(choices=[('08:00', '08h00'), ('12:00', '12h00'), ('18:00', '18h00')], default='08:00', max_length=5, verbose_name="Heure d'envoi")),
                ('min_alerts_to_send', models.PositiveSmallIntegerField(default=1, verbose_name="Nombre minimum d'alertes pour déclencher l'envoi")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Configuration alerte stock',
                'verbose_name_plural': 'Configurations alertes stock',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='unique_alert_config_per_tenant')],
            },
        ),
    ]
