# Generated by Django 6.0.6 on 2026-06-23 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
        ('crm', '0001_initial'),
        ('inventory', '0002_location_stocklevel_stockmovement_unitconversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=32, verbose_name='Référence')),
                ('channel', models.CharField(choices=[('pos', 'Caisse (POS)'), ('whatsapp', 'WhatsApp'), ('online', 'Boutique en ligne'), ('marketplace', 'Marketplace')], default='pos', max_length=20, verbose_name='Canal de vente')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Sous-total')),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Remise totale')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total TTC')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.customer', verbose_name='Client')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.location', verbose_name='Emplacement')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('momo', 'Mobile Money (MTN)'), ('orange_money', 'Orange Money'), ('card', 'Carte bancaire'), ('credit', 'Crédit client'), ('deposit', 'Acompte')], max_length=20, verbose_name='Moyen de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé')], default='confirmed', max_length=20, verbose_name='Statut')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité')),
                ('unit', models.CharField(default='unité', max_length=32, verbose_name='Unité')),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix plancher (snapshot)')),
                ('catalog_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix catalogue (snapshot)')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix final')),
                ('line_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ajustement ligne')),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ajusté par')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.product', verbose_name='Produit')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Vente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'ordering': ['created_at'],
            },
        ),
    ]
