# Generated by Django 6.0.6 on 2026-06-27 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan_subscription_serviceflag'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=32, verbose_name='Référence avoir')),
                ('reason', models.CharField(choices=[('customer_request', 'Demande client'), ('defective', 'Produit défectueux'), ('wrong_item', 'Mauvais article'), ('price_error', 'Erreur de prix'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Motif')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Note')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total avoir')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.sale', verbose_name="Vente d'origine")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantité retournée')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total ligne')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.creditnote', verbose_name='Avoir')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='sales.saleline', verbose_name="Ligne de vente d'origine")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.tenant')),
            ],
            options={
                'verbose_name': "Ligne d'avoir",
                'verbose_name_plural': "Lignes d'avoir",
            },
        ),
    ]
