# Generated by Django 6.0.6 on 2026-06-27 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan_subscription_serviceflag'),
        ('sales', '0002_creditnote_creditnoteline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('tenant', 'reference'), name='unique_credit_note_ref_per_tenant'),
        ),
    ]
